name: partner_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: ^14.0.1   # use latest version
  intl: ^0.19.0
  google_maps_flutter: ^2.4.2
  permission_handler: ^12.0.1
  flutter_svg: ^2.2.1
  pinput: ^5.0.2
  image_picker: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf